name: ProjectKorraSpirits
author: Pride
api-version: 1.19
version: ${project.version}
main: me.pride.spirits.Spirits
description: Spirits but better
depend: [ProjectKorra]
commands:
  spirits:
    description: Default spirits command.
    usage: /spirits [world/orbs]
    permission: spirits.command